uploads = []
generated = []

[[outputs]]
id = "cRiBZpuHVcDD54UeWNoPw"
uri = "file://artifacts/lv-clanad/public/ChequeLogger_Docs_Angular_LVE.zip"
type = "unspecified"
title = "Cheque Logger Docs — Screen Flow + Digest (ZIP)"
